# Generated by Django 4.1.7 on 2023-05-05 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('user_email', models.EmailField(max_length=150)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
