# Generated by Django 5.0.7 on 2024-07-26 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PollsApp', '0003_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(upload_to='media'),
        ),
    ]
